local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>pf", builtin.find_files, { desc = "[p]roject [f]ile search" })
vim.keymap.set("n", "<C-p>", builtin.git_files, { desc = "git repo file search" })
vim.keymap.set("n", "<leader>gf", function()
	builtin.grep_string({ search = vim.fn.input("grep > ") })
end, { desc = "grep files"})
vim.keymap.set("n", "<leader>vf", function()
	builtin.find_files({ cwd = vim.fn.stdpath("config") })
end, { desc = "[V]im [F]ile search" })
